zenangst/Syncalicious

Sources/Application/AppDelegate.swift, Sources/Controllers/ApplicationController.swift, Sources/Controllers/InfoPropertyListController.swift, Sources/Controllers/PreferencesController.swift, Sources/Models/Application.swift, Sources/Models/InfoPropertyList.swift, Sources/Models/Preferences.swift, Syncalicious.xcodeproj/project.pbxproj
Adds the basic infrastructure for resolving, parsing and processing applications from `/Applications` and `~/Applications`.
- It finds all applications located in the folders recursively
- Resolve information from the applications Info.plist and does an attempt to locate the preference file for the application
- It searches for preferences files in `~/Library/Preferences` and `~/Library/Container/~bundleidentifier/Data/Library/`
- If the application has set a defaults domain, then that will be used to resolve the correct plist file.
=> Implement basic infrastructure

Sources/Application/AppDelegate.swift, Sources/Controllers/ApplicationController.swift
Rename `load()` to `loadApplications(at:)`.
It makes the `ApplicationController` more testable and easier to extends.
`applicationDirectories()` has been move into the public API to make it easier to pass the directories as arguments to `loadApplications`.
=> Refactor ApplicationController

Sources/Application/AppDelegate.swift, Sources/Application/DependencyContainer.swift, Sources/Application/MainMenuController.swift, Sources/Controllers/MachineController.swift, Sources/Features/BackupController.swift, Sources/Models/Machine.swift, Syncalicious.xcodeproj/project.pbxproj
This PR adds the initial backup feature, which means it can copy property lists from the installed applications into a selected backup destination. It will create a folder inside using the hostname of the current machine to avoid any backup collisions if you have multiple machines that you want to back up.
=> Implements basic copy phase for backing up property lists

Sources/Features/BackupController.swift
Call .resolveSymlinksInPath() on from path before copying plists.
Fixes https://github.com/zenangst/Syncalicious/issues/6
=> Fix resolving symlinks when backing up plists

.travis.yml, Sources/Application/AppDelegate.swift, Sources/Application/MainMenuController.swift, Sources/Controllers/ApplicationController.swift, Sources/Controllers/PreferencesController.swift, Syncalicious.xcodeproj/project.pbxproj, Syncalicious.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme, TestEnvironment/Applications/ContainerTestApp.app/Contents/Info.plist, TestEnvironment/Applications/ContainerTestAppSUDefaultsDomain.app/Contents/Info.plist, TestEnvironment/Applications/TestApp.app/Contents/Info.plist, TestEnvironment/Applications/TestAppWithSUDefaultsDomain.app/Contents/Info.plist, TestEnvironment/Library/Containers/com.zenangst.Syncalicious.ContainerTestApp/Data/Library/Preferences/6C4433RDLX.group.com.zenangst.Syncalicious.ContainerTestAppSUDefaultsDomain.plist, TestEnvironment/Library/Containers/com.zenangst.Syncalicious.ContainerTestApp/Data/Library/Preferences/com.zenangst.Syncalicious.ContainerTestApp.plist, TestEnvironment/Library/Containers/com.zenangst.Syncalicious.ContainerTestAppSUDefaultsDomain/Data/Library/Preferences/6C4433RDLX.group.com.zenangst.Syncalicious.ContainerTestAppSUDefaultsDomain.plist, TestEnvironment/Library/Preferences/6C4433RDLX.group.com.zenangst.Syncalicious.TestAppWithSUDefaultsDomain.plist, TestEnvironment/Library/Preferences/com.zenangst.Syncalicious.TestApp.plist, Tests/ApplicationControllerTests.swift, Tests/TestController.swift, Tests/Tests.swift
- Refactors implementation to be more testable by injecting environment urls
- Adds `ApplicationControllerTests` which starts testing application scanning and plist parsing
- Adds initial test environment with dummy apps and plist files
=> Feature initial test environment and add tests for ApplicationController

Sources/Application/AppDelegate.swift, Sources/Controllers/InfoPropertyListController.swift, Sources/Models/InfoPropertyList.swift
The UI will now use the `CFBundleName` instead of the bundle identifier.
=> Add bundleName to InfoPropertyList

Sources/Controllers/MachineController.swift, Sources/Features/BackupController.swift, Sources/Features/SyncController.swift, Syncalicious.xcodeproj/project.pbxproj, Tests/ApplicationControllerTests.swift, Tests/Helpers/TestApplicationDelegate.swift, Tests/Helpers/TestController.swift, Tests/Helpers/TestHost.swift, Tests/SyncControllerTests.swift
Adds a new SyncController class, this class is in charge of handling the sync setups and desyncing on an app-per-app basis. When the sync is enabled for an application the following steps are performed:
- Backup the current configuration file in a directory using the current computer name.
- Create a Storage directory if it doesn't already exist.
- Copies the property list into the sync folder (only if it doesn't already exist)
- Removes the current plist and creates a symlink pointing to the sync folder.
When an application is marked as unsynchronised, the following occurs:
- Remove the symlinked preferences file
- Copy the sync backup file to the preference file location
- Remove the sync backup file for that specific computer
=> Add initial implementation of sync feature

Syncalicious.xcodeproj/project.pbxproj, Tests/ApplicationControllerTests.swift, Tests/BackupControllerTests.swift, Tests/Helpers/TestController.swift, Tests/SyncControllerTests.swift
- Adds `testInitializeBackup`
- Adds convenience urls on  `TestController`
- Adds `tearDown` to clean up sync folder in `SyncControllerTests`
=> Add BackupControllerTests and improve other tests

Sources/Views/MainWindow.swift
Fixes issue that the main window doesn't have a proper size the first time the app runs.
=> Set frame size of window to minimum size on first run

Sources/Controllers/ApplicationController.swift
Safe-guard against duplicates by keeping an index of bundle identifiers.
=> Remove duplicate applications from list

Sources/Application/AppDelegate.swift
- Fixes issue where apps that start with a lowercase letter; like iTunes, ended up last in the list.
=> Lowercase the bundle name before sorting

Sources/Application/AppDelegate.swift, Sources/Application/DependencyContainer.swift, Sources/Application/MainMenuController.swift, Sources/Factories/CollectionViewLayoutFactory.swift, Sources/Factories/ViewControllerFactory.swift, Sources/Factories/WindowFactory.swift, Syncalicious.xcodeproj/project.pbxproj
- Adds `CollectionViewLayoutFactory` for creating layouts
- Adds `ViewControllerFactory` for constructing view controllers
- Adds `WindowFactory` windows, window controllers and alerts.
The motivation behind this PR is to contain the creation of objects into their rightful place. It offloads the application delegate with all application creation and separates the concerns. This will be more useful in the future for things like third-party dependency containment.
=> Introduce factories

Sources/Application/AppDelegate.swift, Sources/Controllers/InfoPropertyListController.swift, Sources/Models/InfoPropertyList.swift
- Adds `bundleVersion` and `versionString` to `InfoPropertyList`
- Use version(s) instead of bundle identifier in list of applications
=> Improve application list

Sources/Application/AppDelegate.swift, Sources/Controllers/MachineController.swift, Sources/Features/Core/SyncController.swift
- `MachineController` is no longer dependent on `ShellController`
- Improves idle syncing collision by checking if the machine is active or not
=> Improve idle syncing

Sources/Features/Core/SyncController.swift
- Fixes issue where symlinks get copied instead of actual property lists. This is solved by resolving the correct path before copying the file over.
=> Resolve symlink before copy

Sources/Controllers/SplitViewController.swift
The split view was rendered with 2 pixel offset, this is fixed by changing the constraints to 38 instead of 40.
=> Fix splitView offset rendering

Sources/Controllers/SyncController.swift, Sources/Features/Operations/CoreOperation.swift
- Fix accessing `dockTile` in a background thread
- Refactor `CoreOperation` to avoid crashing
=> Improve sync

Sources/Features/Operations/OperationController.swift
- Cancelled operations will no longer be used when checking if the operation queue is executing
=> Refactor `isExecuting` property

Sources/Features/Detail/DetailContainerViewController.swift
Fixes visual bug where the computer view doesn't get a background color that stretches the entire width.
=> Set background color to computer view controller

Resources/Info.plist, Sources/Controllers/SplitViewController.swift, Sources/Controllers/ViewController.swift, Sources/Factories/CollectionViewLayoutFactory.swift, Sources/Factories/WindowFactory.swift, Sources/Features/Application List/ApplicationListItem.swift, Sources/Features/Application List/ListContainerViewController.swift, Sources/Features/Application List/ListFeatureViewController.swift, Sources/Features/Detail/DetailContainerViewController.swift, Sources/Features/Detail/DetailFeatureViewController.swift, Sources/Views/BackgroundView.swift, Sources/Views/SearchField.swift, Sources/Views/SplitView.swift, Syncalicious.xcodeproj/project.pbxproj
- The list items now have less height to fit more applications on screen, this results in less scrolling when using the application
- The search field is now styled after the upcoming macOS Catalina release, this is mostly done by reducing the amount of corner radius that the view gets
- The application now supports both light and dark appearance
- The side menu (the application list) now uses a `NSVisualEffectView`
- The feedback button now uses a regular `NSButton`
=> Improve UI to support dark mode

Podfile.lock, Sources/Features/Application List/ListContainerViewController.swift, Sources/Features/Detail/DetailContainerViewController.swift
- Update Family framework version to 0.22.5
- Update Blueprints framework version to 0.13.1
- Leverage from framework convenience
=> Use newest version of Family framework

Sources/Features/Detail/DetailFeatureViewController.swift
- Set `itemsPerRow` to `2.25` if the user has more than 2 computers in the list, this adds a bit of hinting that there is more content available
=> Improve computer layout
