zenangst/Syncalicious

- Resources/Base.lproj/MainMenu.xib
- Sources/Application/AppDelegate.swift
- Sources/Application/DependencyContainer.swift
- Sources/Application/MainMenuController.swift
- Sources/Controllers/ApplicationController.swift
- Sources/Extensions/UserDefaults+Extensions.swift
- Sources/Features/BackupController.swift
- Syncalicious.xcodeproj/project.pbxproj
- Introduces `DependencyContainer`
- Refactors `ApplicationController` to use dependency injection
- Adds extension on `UserDefaults` to store backup location
- Adds initial skeleton implementation for `BackupController`
- Features a new `MainMenuController` which acts as the responder to `MainMenu.xib`
> Add skeleton implementation for backup controller

- Sources/Application/AppDelegate.swift
- Sources/Features/BackupController.swift
Adds `BackupControllerDelegate` to decouple the feature from knowing about `UserDefaults`.
> Improve BackupController with delegate

- .travis.yml
- Syncalicious.xcodeproj/project.pbxproj
- Syncalicious.xcodeproj/xcshareddata/xcschemes/Syncalicious.xcscheme
This adds a `.travis.yml` file so that each PR will check that the source code builds.
Will add tests and run them on Travis later on.
> Start running builds on travis-ci.com

- Sources/Application/AppDelegate.swift
- Sources/Controllers/ViewController.swift
- Sources/Toolbar/TitleToolbarItem.swift
- Sources/Toolbar/Toolbar.swift
- Sources/Views/MainWindow.swift
- Syncalicious.xcodeproj/project.pbxproj
Adds an implementation for the applications main window with a very basic toolbar to go with it.
> Implements a base window and toolbar

- .travis.yml
- Resources/Info-Tests.plist
- Sources/Application/AppDelegate.swift
- Sources/Controllers/ViewController.swift
- Syncalicious.xcodeproj/project.pbxproj
- Syncalicious.xcodeproj/xcshareddata/xcschemes/Syncalicious.xcscheme
- Tests/Tests.swift
- Adds a new target to be able to run tests
- Configures Travis to run the tests
> Add test target to start running tests on Travis

- .swiftlint.yml
- Sources/Application/AppDelegate.swift
- Sources/Controllers/PreferencesController.swift
- Sources/Features/BackupController.swift
- Sources/Toolbar/Toolbar.swift
- Syncalicious.xcodeproj/project.pbxproj
- Adds SwiftLint
- Fixes linter warnings
> Feature SwiftLint

- .sourcery.yml
- Generated/CollectionViewItemComponent.generated.swift
- Sourcery/Protocols/CollectionViewItemComponent.swift
- Sourcery/Templates/CollectionViewItemComponent.stencil
- Sources/Application/AppDelegate.swift
- Sources/Application/DependencyContainer.swift
- Sources/Features/BackupController.swift
- Sources/Features/IconController.swift
- Sources/Protocols/Component.swift
- Sources/Views/ApplicationView.swift
- Syncalicious.xcodeproj/project.pbxproj
- Adds initial collection view rendering of the applications
- Uses Sourcery to construct the collection view
> Implements basic collection view using Sourcery

- Sources/Features/IconController.swift
- Sources/Views/ApplicationView.swift
- Properly create icon cache directory if it does not exist
- Add width and height constraints to the application icon view
> Improve loading icons

- Podfile.lock
- Sources/Controllers/SplitViewController.swift
- Sources/Features/Application Detail/ApplicationDetailFeatureViewController.swift
- Sources/Features/Application Detail/ApplicationDetailInfoViewController.swift
- Sources/Views/DividerView.swift
This PR starts implementing support for dark mode.
It is not the prettiest thing in the world but it does the job, somewhat.
There are some bugs with a chicken and egg situation with split view controllers which I intend to refactor later.
> Minor improvements to dark mode

- Sources/Controllers/SplitViewController.swift
> Remove double divider in the `SplitViewController`

- Podfile.lock
- Differific (0.7.0)
Enables animations
- Family (0.14.6)
Fixes rendering issues
> Pod update Differific & Family

- Sources/Features/Application Detail/ApplicationDetailInfoViewController.swift
- Sources/Features/First Launch/WelcomeView.swift
- Sources/Views/Button.swift
- Syncalicious.xcodeproj/project.pbxproj
> Implement custom NSButton called Button

- Sources/Factories/CollectionViewLayoutFactory.swift
> Improve application list layout

- Sources/Application/AppDelegate.swift
- Sources/Application/MainMenuController.swift
- Sources/Controllers/ViewController.swift
- Sources/Extensions/NSLayoutConstraint+Extensions.swift
- Sources/Factories/AnimationFactory.swift
- Sources/Features/Application Detail/ApplicationDetailInfoViewController.swift
- Sources/Features/Application List/ApplicationListSearchViewController.swift
- Sources/Features/Application List/ApplicationListSortViewController.swift
- Sources/Features/First Launch/DestinationViewController.swift
- Sources/Features/First Launch/FirstLaunchViewController.swift
- Sources/Features/First Launch/PermissionViewController.swift
- Sources/Features/First Launch/WelcomeViewController.swift
- Sources/Features/First Launch/WelcomeWindow.swift
- Syncalicious.xcodeproj/project.pbxproj
- Introduces animation factory to reduce code duplication and unify animation properties
- Refactors the welcome flow to use view controllers instead of regular views
- Minor refactoring to the app delegate
- Fixes warnings
> Refactor welcome flow to use view controllers

- Podfile.lock
- Sources/Application/AppDelegate.swift
- Sources/Application/AppDelegateController.swift
- Sources/Application/MainMenuController.swift
- Sources/Views/MainWindow.swift
- Syncalicious.xcodeproj/project.pbxproj
Refactors the app delegate implementation and moves the majority over into a new class called `ApplicationDelegateController`. It also updates to a new version of `Family` which improves the scrolling experience and fixes a bunch of content size related bugs.
> Introduce ApplicationDelegateController

- Generated/CollectionViewItemComponent.generated.swift
- Podfile.lock
- Sources/Factories/CollectionViewLayoutFactory.swift
- Sources/Factories/ViewControllerFactory.swift
- Sources/Factories/WindowFactory.swift
- Sources/Features/Application Detail/ApplicationDetailFeatureViewController.swift
- Sources/Features/Application List/ApplicationListFeatureViewController.swift
- Sources/Features/Application List/ApplicationListItem.swift
- Sources/Views/MainWindow.swift
- Update frameworks to fix window resizing, content size issues and scrolling past the maximum content size
- Move icon loading to `willDisplay`
- Reduce dependency of list controller in feature controller
> Improve performance and bug fixing

- Sources/Application/AppDelegateController.swift
- Sources/Extensions/UserDefaults+Extensions.swift
If `backupWhenIdle` is set to true, then the machine will backup all selected applications
> Add backupWhenIdle feature

- Generated/CollectionViewItemComponent.generated.swift
- Podfile.lock
- Sources/Controllers/InfoPropertyListController.swift
- Sources/Controllers/PreferencesController.swift
- Sources/Controllers/SplitViewController.swift
- Sources/Extensions/NSDictionary+Extensions.swift
- Sources/Factories/CollectionViewLayoutFactory.swift
- Sources/Factories/ViewControllerFactory.swift
- Sources/Features/Application Detail/ApplicationDetailContainerViewController.swift
- Sources/Features/Application Detail/ApplicationDetailFeatureViewController.swift
- Sources/Features/Application Detail/ApplicationDetailInfoViewController.swift
- Sources/Features/Application Detail/States/Application/ApplicationKeyboardBindingItem.swift
- Sources/Features/Application List/ApplicationListItem.swift
- Sources/Features/Application List/ApplicationListSearchViewController.swift
- Sources/Models/Application.swift
- Sources/Models/ApplicationPropertyList.swift
- Sources/Models/Preferences.swift
- Syncalicious.xcodeproj/project.pbxproj
> Feature initial implementation of keyboard bindings

- Sources/Application/AppDelegate.swift
Don't load InjectionIII bundle if app is located in /Applications
> Improve InjectionIII setup

- Podfile.lock
- Sources/Application/AppDelegateController.swift
- Sources/Application/DependencyContainer.swift
- Sources/Controllers/KeyboardController.swift
- Sources/Factories/CollectionViewLayoutFactory.swift
- Sources/Factories/ViewControllerFactory.swift
- Sources/Features/Application Detail/ApplicationDetailContainerViewController.swift
- Sources/Features/Application Detail/ApplicationDetailFeatureViewController.swift
- Sources/Features/Application Detail/States/Application/Controllers/KeyHolderController.swift
- Sources/Features/Application Detail/States/Application/Data sources/ApplicationKeyboardBindingDataSource.swift
- Sources/Features/Application Detail/States/Application/Models/ApplicationKeyboardBindingModel.swift
- Sources/Features/Application Detail/States/Application/View Controllers/ApplicationKeyboardActionsViewController.swift
- Sources/Features/Application Detail/States/Application/View Controllers/ApplicationKeyboardBindingViewController.swift
- Sources/Features/Application Detail/States/Application/Views/ApplicationKeyboardBindingItem.swift
- Sources/Views/Button.swift
- Syncalicious.xcodeproj/project.pbxproj
Builds on the keyboard shortcut feature and implements temporary in memory storage
of unsaved changes. The feature is still not complete as it is missing the save functionality.
Discarding changes per-app is implemented.
> Continue keyboard shortcut implementation

- Resources/Base.lproj/MainMenu.xib
- Sources/Application/AppDelegate.swift
- Sources/Application/AppDelegateController.swift
- Sources/Application/MainMenuController.swift
- Sources/Controllers/SplitViewController.swift
- Sources/Factories/WindowFactory.swift
- Sources/Features/Application Detail/States/Application/View Controllers/ApplicationKeyboardActionsViewController.swift
- Sources/Features/Application List/ApplicationListItem.swift
- Sources/Features/Application List/ApplicationListSearchViewController.swift
- Sources/Views/SearchField.swift
- Add toggleSidebar functionality
- Properly hide decoration views when collapsing split items
- Improve look and feel of the list search field
- Minor refactoring of ApplicationKeyboardActionsViewController
> Various improvements

- Sourcery/Templates/CollectionViewItemComponent.stencil
- Sources/Controllers/ApplicationController.swift
- Sources/Controllers/MachineController.swift
- Sources/Controllers/SyncController.swift
- Sources/Factories/CollectionViewLayoutFactory.swift
- Sources/Factories/OperationFactory.swift
- Sources/Features/Operations/CoreOperation.swift
- Sources/Features/Operations/DispatchOperation.swift
- Sources/Features/Operations/OperationController.swift
- Tests/Helpers/TestController.swift
- Refactor operations
- Minor UI changes
- Improve switching states
- Exclude applications based on keywords
- Remove duplicate entries in the application list
- Minor bug-fixes to the stencil template
> Refactor implementation to fix issues with syncing

- Generated/CollectionViewItemComponent.generated.swift
- Podfile.lock
- Sourcery/Templates/CollectionViewItemComponent.stencil
- Sources/Controllers/ApplicationController.swift
- Sources/Controllers/IconController.swift
- Sources/Features/Application List/ApplicationListItem.swift
- Sources/Features/Application List/ListContainerViewController.swift
- Sources/Features/Detail/DetailContainerViewController.swift
- Sources/Views/HStack.swift
- Sources/Views/ImageView.swift
- Sources/Views/OpaqueView.swift
- Sources/Views/SpacerView.swift
- Sources/Views/StackView.swift
- Sources/Views/TextField.swift
- Sources/Views/VStack.swift
- Syncalicious.xcodeproj/project.pbxproj
- Syncalicious.xcodeproj/xcshareddata/xcschemes/Syncalicious.xcscheme
- Syncalicious.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
- Tests/Helpers/TestController.swift
- Improves overall structure of the project
- Improves startup time by fixing dispatch bug
- Enables animations
- Some minor syntax updates when using frameworks
> Various internal improvements

- Sources/Extensions/NSView+Extensions.swift
- Sources/Features/General/GeneralInfoViewController.swift
- Syncalicious.xcodeproj/project.pbxproj
Configure compression resistance and hugging priority on labels in the general info view controller.
> Improve layout by setting compression resistance

- Generated/CollectionViewItemComponent.generated.swift
- Generated/PrototypeItemComponent.generated.swift
- Resources/Info.plist
- Sourcery/Templates/CollectionViewItemComponent.stencil
- Sources/Features/Detail/DetailFeatureViewController.swift
- Syncalicious.xcodeproj/project.pbxproj
- Adds new feedback button that opens a new issue on GitHub
- Disables multiple selection feature
> Add feedback button

- Resources/Base.lproj/MainMenu.xib
- Sources/Application/MainMenuController.swift
- Adds release notes menu item
- Adds current version menu item
- Adds report new issue menu item
> Implement new menu items

- Sources/Features/First Launch/PermissionViewController.swift
- Sources/Features/First Launch/WelcomeViewController.swift
- Syncalicious.xcodeproj/project.pbxproj
> Refactor tutorial to fix colors in dark mode

- Sources/Features/Application List/ApplicationListItem.swift
- Reconfigures the stack views to vertically align the content
- Restricts the title label to maximum number of lines to 1
- Set line break mode on title label
- Fixes #104
> Refactor application list item

- Podfile.lock
The new version to use is 0.20.8
> Update Family framework

- Sources/Controllers/ApplicationController.swift
- Add new system directory to include new applications on macOS Catalina
> Add system applications directory

- Sources/Controllers/SyncController.swift
- Iterate over all folders before removing applications that have been active
> Fix syncing multiple machines issue
